name: export

on:
  workflow_dispatch:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: 'Hardware/*.sch'
      # optional - PCB design file
        board: 'Hardware/*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: gerbers.kibot.yaml
        dir: docs
        schema: 'Hardware/*.sch'
        board: 'Hardware/*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: model.kibot.yaml
        dir: docs
        schema: 'Hardware/*.sch'
        board: 'Hardware/*.kicad_pcb'
    - uses: nerdyscout/kicad-exports@v2.2
      with:
        config: plot.kibot.yaml
        dir: docs
        schema: 'Hardware/*.sch'
        board: 'Hardware/*.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
